# Generated by Django 3.2.8 on 2021-10-13 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commentsection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='dislikes',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='comments',
            name='likes',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='comments',
            name='message',
            field=models.CharField(blank=True, default='', max_length=280, null=True),
        ),
        migrations.AddField(
            model_name='replies',
            name='message',
            field=models.CharField(blank=True, default='', max_length=280, null=True),
        ),
    ]
