# Generated by Django 3.2.8 on 2021-10-13 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('commentsection', '0002_auto_20211013_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='replies',
            name='comment_id',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='commentsection.comments'),
        ),
    ]
