# Generated by Django 3.2.8 on 2021-10-14 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commentsection', '0003_replies_comment_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='replies',
            old_name='comment_id',
            new_name='comment',
        ),
    ]
