# Generated by Django 3.2.8 on 2021-10-14 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commentsection', '0004_rename_comment_id_replies_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='video',
            field=models.CharField(max_length=280, null=True),
        ),
    ]
